# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from typing import Literal

from fastapi import Depends
from sqlalchemy import func, select

from src.config.config_service import config_service
from src.common.dto.pagination_response_dto import PaginationResponseDto
from src.users.dto.user_create_dto import UserCreateDto, UserUpdateRoleDto
from src.users.dto.user_search_dto import UserSearchDto
from src.users.repository.user_repository import UserRepository
from src.users.user_model import User, UserModel, UserRoleEnum
import logging

logger = logging.getLogger(__name__)


class UserService:
    """Handles the business logic for user management."""

    def __init__(self, user_repo: UserRepository = Depends()):
        self.user_repo = user_repo

    @staticmethod
    def _role_name(role: UserRoleEnum | str) -> str:
        return role.value if isinstance(role, UserRoleEnum) else str(role)

    @classmethod
    def _has_admin_role(cls, roles: list[UserRoleEnum | str]) -> bool:
        return any(cls._role_name(role).lower() == "admin" for role in roles)

    async def _should_bootstrap_admin(self, email: str) -> bool:
        configured_admin = (
            (config_service.ADMIN_USER_EMAIL or "").strip().lower()
        )
        # If explicitly configured, only that email gets auto-admin.
        if configured_admin and configured_admin != "system":
            return email.lower() == configured_admin

        # Safety fallback for fresh environments: ensure at least one admin exists.
        admin_query = (
            select(func.count())
            .select_from(User)
            .where(User.roles.contains(["admin"]))
        )
        admin_count_result = await self.user_repo.db.execute(admin_query)
        admin_count = admin_count_result.scalar() or 0
        return admin_count == 0

    async def create_user_if_not_exists(
        self,
        email: str,
        name: str,
        picture: str | None,
    ) -> UserModel:
        """Retrieves a user by their email. If the user exists, it returns it.
        If the user is soft-deleted, it restores them.
        If the user doesn't exist, it creates a new user document.
        """
        normalized_email = email.strip().lower()

        # 1. Check if the user already exists in the database (including deleted).
        existing_user = await self.user_repo.get_by_email(
            normalized_email, include_deleted=True
        )

        if existing_user:
            # Restore soft-deleted user
            if existing_user.deleted_at is not None:
                logger.info(
                    "Restoring soft-deleted user during login: %s", normalized_email
                )
                await self.user_repo.restore(existing_user.id)
                existing_user = await self.user_repo.get_by_id(existing_user.id)

            if await self._should_bootstrap_admin(
                normalized_email
            ) and not self._has_admin_role(existing_user.roles):
                updated_roles = [
                    self._role_name(role) for role in existing_user.roles
                ]
                updated_roles.append(UserRoleEnum.ADMIN.value)
                existing_user = await self.user_repo.update(
                    existing_user.id,
                    {"roles": updated_roles},
                )
            return existing_user

        # 2. If the user does not exist, create a new User using UserCreateDto
        #    ID will be auto-generated by the DB
        new_user_dto = UserCreateDto(
            email=normalized_email,
            name=name,
            picture=picture or "",
        )

        # We need to ensure roles are set, but UserCreateDto doesn't have roles.
        # The repository create method takes a Pydantic model or dict.
        # If we pass UserCreateDto, we miss 'roles'.
        # We can pass a dict that includes roles.
        user_data = new_user_dto.model_dump()
        user_data["roles"] = [UserRoleEnum.USER]

        if await self._should_bootstrap_admin(normalized_email):
            user_data["roles"].append(UserRoleEnum.ADMIN)

        # 3. Call the repository's create() method
        return await self.user_repo.create(user_data)

    async def ensure_user_is_platform_admin(self, user_id: int) -> UserModel:
        """Ensures a user has the platform admin role."""
        existing_user = await self.user_repo.get_by_id(user_id)
        if not existing_user:
            from fastapi import HTTPException

            raise HTTPException(status_code=404, detail="User not found.")

        if self._has_admin_role(existing_user.roles):
            return existing_user

        updated_roles = [
            self._role_name(role) for role in existing_user.roles
        ]
        if UserRoleEnum.USER.value not in updated_roles:
            updated_roles.append(UserRoleEnum.USER.value)
        if UserRoleEnum.ADMIN.value not in updated_roles:
            updated_roles.append(UserRoleEnum.ADMIN.value)
        return await self.user_repo.update(user_id, {"roles": updated_roles})

    async def create_or_restore_user_by_email_for_admin(
        self,
        email: str,
    ) -> tuple[UserModel, Literal["created", "existing", "restored"]]:
        """Creates (or restores) a user profile by email for admin actions.

        Returns a tuple of (user, provisioning_status).
        """
        normalized_email = email.strip().lower()

        existing_user = await self.user_repo.get_by_email(
            normalized_email,
            include_deleted=True,
        )
        if existing_user:
            if existing_user.deleted_at is not None:
                await self.user_repo.restore(existing_user.id)
                existing_user = await self.user_repo.get_by_id(existing_user.id)
                return existing_user, "restored"
            return existing_user, "existing"

        # Derive a deterministic display name from email local part.
        local_part = normalized_email.split("@", maxsplit=1)[0].replace(
            ".", " "
        )
        local_part = local_part.replace("_", " ").replace("-", " ")
        derived_name = " ".join(segment for segment in local_part.split() if segment)
        if len(derived_name) < 2:
            derived_name = "User"

        created = await self.create_user_if_not_exists(
            email=normalized_email,
            name=derived_name.title(),
            picture=None,
        )
        return created, "created"

    async def get_user_by_id(self, user_id: int) -> UserModel | None:
        """Finds a single user by their ID."""
        return await self.user_repo.get_by_id(user_id)

    async def find_all_users(
        self,
        search_dto: UserSearchDto,
    ) -> PaginationResponseDto[UserModel]:
        """Retrieves a paginated list of all users."""
        return await self.user_repo.query(search_dto)

    async def delete_user(
        self, user_id: int, deleted_by: int | None = None
    ) -> bool:
        """Soft deletes a user.
        
        Before deletion, checks if user owns any workspaces. If they own any,
        transfers ownership to another admin to prevent cascade deletion of groups.
        """
        from src.workspaces.schema.workspace_model import Workspace

        # Reuse the existing db session from user_repo
        db = self.user_repo.db

        # Check if user owns any workspaces
        stmt = select(Workspace).where(Workspace.owner_id == user_id)
        result = await db.execute(stmt)
        owned_workspaces = result.scalars().all()

        if owned_workspaces:
            # Find another admin to transfer ownership to
            admin_query = (
                select(User)
                .where(User.roles.contains(["admin"]))
                .where(User.id != user_id)
                .where(User.deleted_at == None)  # noqa: E711
                .limit(1)
            )
            admin_result = await db.execute(admin_query)
            admin_user = admin_result.scalar_one_or_none()

            if admin_user:
                logger.info(
                    "Transferring %d workspaces from user %d to admin %d",
                    len(owned_workspaces), user_id, admin_user.id,
                )
                from sqlalchemy import update
                update_stmt = (
                    update(Workspace)
                    .where(Workspace.owner_id == user_id)
                    .values(owner_id=admin_user.id)
                )
                await db.execute(update_stmt)
                await db.commit()
            else:
                logger.warning(
                    "Cannot delete user %d: owns %d workspaces and no admin available",
                    user_id, len(owned_workspaces),
                )
                return False

        return await self.user_repo.soft_delete(user_id, deleted_by=deleted_by)

    async def restore_user(self, user_id: int) -> bool:
        """Restores a soft-deleted user."""
        return await self.user_repo.restore(user_id)

    async def update_user_role(
        self,
        user_id: int,
        role_data: UserUpdateRoleDto,
    ) -> UserModel | None:
        """Updates the role of a specific user with safeties."""
        from fastapi import HTTPException
        from sqlalchemy import func, select

        from src.users.user_model import User

        existing_user = await self.user_repo.get_by_id(user_id)
        if not existing_user:
            return None

        was_admin = "admin" in existing_user.roles
        will_be_admin = "admin" in [role.value for role in role_data.roles]

        if was_admin and not will_be_admin:
            admin_query = (
                select(func.count())
                .select_from(User)
                .where(User.roles.contains(["admin"]))
            )
            admin_count_result = await self.user_repo.db.execute(admin_query)
            admin_count = admin_count_result.scalar() or 0
            if admin_count <= 1:
                raise HTTPException(
                    status_code=400,
                    detail="There must be at least 1 admin on the app.",
                )

        roles_as_strings = [role.value for role in role_data.roles]
        return await self.user_repo.update(user_id, {"roles": roles_as_strings})
